### ISSUE TITLE
BaseDecorator needs documentation and more convenient methods

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-auto-instr-java#104]
The BaseDecorator needs some rework. In particular, I would like to address this:

- [ ] Better handling of the default tracer and removing the need to declare the tracer separately in each subclass.
- [ ] Add convenience methods for starting spans, creating scopes, injecting/extracting attributes etc.
- [ ] Add javadoc to all public methods.
- [ ] Remove redundant/unused methods.

Some details. Please comment if I'm getting this wrong.
* ```BaseDecorator::beforeFinish()``` doesn't do anything and there are no implementations in subclasses. I suggest we remove this method as it is called in the critical path of every interaction. If an instrumenter needs some specific handling of span finishing, it should (and already does) implement that directly.
*  The code in ```BaseDecorator::afterStart()``` should be moved to the suggested new method ```BaseDecorator::beginSpan()``` eliminating a method call from most instrumenters.
*  ```BaseDecorator::instrumentationNames()``` is never called and it's not clear whether it's needed. Should we remove?
* The entire idea of implementing specialized handling of instrumentation both by subclassing the decorator and by implementing specific functionality in Advice-methods feels a bit redundant and confusing to me. There was probably a really good and sound design idea behind this in the beginning, but it seems that, over time, many instrumenters are implemented according to different design principles. Putting this here as a topic for discussion.

Please assign this to me.

**Comment by trask** [comment]
@prydin Ok to close this and revisit if needed after #45?

**Comment by prydin** [comment]
Closing it.
