### ISSUE TITLE
Change naming to standard get/set pattern

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-auto-instr-java#105]
Throughout the code, there are some methods that get things but that don't have the getX naming pattern. I believe that pattern is used in the opentelemetry-java project, so we should follow the same standard. Examples are ```instrumentationNames()```, ```component()``` and ```spanType()```.

If we have already made a decision to not use the getX-naming, please disregard and close this issue!

**Comment by trask** [comment]
👍 I agree we should follow same convention as opentelemetry-java

**Comment by prydin** [comment]
Resolved.
