### ISSUE TITLE
Please add me as member of opentelemetry-auto-instr-java

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-auto-instr-java#120]
Dear friends!

I hereby request to be added as a member of this project. My sponsors are @trask and @tylerbenson 

Thank you!

**Comment by trask** [comment]
+1

**Comment by trask** [comment]
Oh, wrong repo :-), need to open this in community repo

**Comment by prydin** [comment]
Oh bummer! :)
