### ISSUE TITLE
Apply OpenTelemetry semantic conventions for HTTP

### ISSUE THREAD

**Issue by hanwavefront** [open-telemetry/opentelemetry-auto-instr-java#136]
Subtask of #130.  Modify existing instrumentation to conform to OpenTelemetry semantic conventions for HTTP spans.

Http Clients:

- [ ] Akka HTTP
- [ ] Apache HttpClient
- [ ] Apache HttpAsyncClient
- [ ] AWS SDK
- [ ] Google HTTP Client
- [ ] HttpURLConnection
- [ ] JAX-RS Client
- [ ] Netty
- [ ] OkHttp
- [ ] Play WS

Http Servers:

- [ ] Akka HTTP
- [ ] Finatra
- [ ] Grizzly
- [ ] JAX-RS
- [ ] Jetty
- [ ] Netty
- [ ] OkHttp
- [ ] Play
- [ ] Ratpack
- [ ] Servlet

**Comment by trask** [comment]
These are my thoughts for `net.peer.name` and `net.peer.ip`:

* For outgoing calls (HTTP Clients) we typically have an unresolved name and should set `net.peer.name`, but not `net.peer.ip` which could trigger DNS lookup
* For incoming calls (Http Servers) we typically have an IP address and should set `net.peer.ip`, but not `net.peer.name` which could trigger reverse DNS lookup

**Comment by hanwavefront** [comment]
@trask sounds good.

Here are the items I'm working on:

Client
- [ ] Set `net.peer.name` and `net.peer.port` instead of `peer.hostname` and `peer.port` (the specs are a bit unclear on which set to use, but this should be more consistent with other resource types)
- [ ] Update span names to include the request method, i.e. `HTTP {METHOD_NAME}`

Server
- [ ] Set `net.peer.ip` instead of `peer.ipv4` and `peer.ipv6`
- [ ] Update span names to be the matched routes, e.g. `GET /api/users/{user_id}`, or `HTTP {METHOD_NAME}` when the route is not accessible

Both
- [ ] Update `http.url` to include the query string and fragment if available
