### ISSUE TITLE
CircleCI tests fail on certain test tasks

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-auto-instr-java#173]
Consider the following file:

https://github.com/prydin/opentelemetry-auto-instr-java/blob/prydin-dynamic-jaeger/exporter-adapters/exporter-adapters.gradle

It contains this section: 

```
test {
  dependsOn 'dummy-exporter-adapter:shadowJar'
  dependsOn 'jaeger-adapter:shadowJar'
  systemProperty 'projectVersion', allprojects.version[0]
  systemProperty 'adapterRoot', "${rootDir}/exporter-adapters"
}
```

This test works fine on my laptop with any supported java version, but fails in CircleCI due to the system properties never being set. We have noticed that instead of running the regular ```test``` task, CircleCI seems to run some dynamically generated task called ```testJava11Generated```. It appears that when this task is run, the statements under the ```test``` task section of the gradle script above are never executed.

Looking through the source code, I'm noticed that ```testJava11Generated``` never seems to appear in any file, leading me to believe that this is something that CircleCI generates.

@tylerbenson Is probably the person holding the keys to this, so I take the liberty of tagging him! :)

**Comment by prydin** [comment]
It looks like the solution to this is never to use the ```test``` shorthand, but use this instead: ```tasks.withType(Test).configureEach {``` as this appears to pick up any type of test.

Is this the intended behavior? In that case I can close the issue.

**Comment by prydin** [comment]
I spoke too soon. Now the dependencies aren't resolved. Again, it works on my laptop with Java 11. 

Here's the PR I'm trying to get through: https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/171

**Comment by tylerbenson** [comment]
@prydin The `testJavaX` tasks are dynamically generated by gradle when the appropriate environment variable is set: https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/gradle/java.gradle#L287

You need to add something like `JAVA_11_HOME` to have that generated.

The config you initially added was only updating the main test task, not the generated ones.

If you have any better ideas on how to do this, please let me know.

**Comment by prydin** [comment]
Thanks. Any ideas why it’s not picking up the dependencies when I don it with the tasks.withType...? It runs the systemProperties but doesn’t seem to catch the dependsOn correctly.

**Comment by prydin** [comment]
> If you have any better ideas on how to do this, please let me know.

How about a subclassed custom test task that installs itself in place of ```test``` kind of like ```shadowJar``` installs itself in place of ```jar```? I'm not that great at gradle, so maybe I'm missing something.

**Comment by prydin** [comment]
I worked around this. @tylerbenson I don't think I can find a better way of doing this. The gradle spec is pretty strict on each task only doing a single distinct operation, so generating new tasks seems to be the only way to add a open-ended number of tasks at compile-time. 

Closing this.
