### ISSUE TITLE
Review semantic conventions for databases 

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-auto-instr-java#194]
Make sure appropriate attributes are populated with the correct tag names.

This is a subtask of #130 

- [x] Couchbase - Added ```db.statement``` and ```db.instance```
- [x] Cassandra - Appears to be compliant
- [x] Elasticsearch - Appears to be compliant. Poor test coverage!
- [x] Hibernate - Appears to be compliant
- [x] JDBC - Appears to be compliant
- [x] Jedis - Appears to be compliant
- [x] Mongo - Appears to be compliant
- [x] Memcached - Appears to be compliant

**Comment by trask** [comment]
Awesome! Closing this.
