### ISSUE TITLE
Road map to v0.1.0

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-auto-instr-java#22]
1. Remove functionality that should be delegated to the OpenTelemetry SDK / Exporters (#16) ✔️
   * The goal of doing this first is that it reduces the surface area that we have to work across during subsequent steps.
2. Remove OpenTracing interoperability (#6) ✔️
   * The goal of doing this next is to strip away the abstraction layer that it brings, and to further reduce the surface area, leaving behind only code that is used by the instrumentation.
3. Remove continuation feature (#48) ✔️
   * There's no equivalent OpenTelemetry API feature, so it will makes things easier if we remove this before switching over to OpenTelemetry API.
4. Change instrumentation to use OpenTelemetry API (indirectly) (#43) ✔️
   * This is a big milestone!
5. Rename package to io.opentelemetry.auto (#7) ✔️
6. Change instrumentation to use OpenTelemetry API directly (#12) ✔️
   * So we can start work on sharing code between auto and contrib instrumentation (#45)
7. Support the Jaeger exporter (#115) ✔️
   * After this, the project should be ready for end users to start testing!
8. Release `v0.1.0`

**Comment by trask** [comment]
Inserted "Change instrumentation to use OpenTelemetry API directly" (#12) into the list above (reason documented in the list).

**Comment by trask** [comment]
Changed "Change instrumentation to use OpenTelemetry API directly" (#12) to Change instrumentation to use OpenTelemetry API _indirectly_ (#43), which will give us OpenTelemetry exporter support (and `v0.1.0` release) sooner. We will come back to #43 after `v0.1.0`.

**Comment by prydin** [comment]
Do you need help?

**Comment by trask** [comment]
Hi @prydin, definitely! Any chance you can join the weekly [Thursday 9am Pacific meeting](https://calendar.google.com/calendar/embed?src=google.com_b79e3e90j7bbsa2n2p5an5lf60%40group.calendar.google.com) to chat?

**Comment by prydin** [comment]
Yeah, I'll get on that call. Looking forward to it!

**Comment by trask** [comment]
Changed "Support using this project directly and supplying your own OpenTelemetry exporter (#8)" to "Support the Jaeger exporter (#115)". We will revisit #8 in v0.2.0.

**Comment by trask** [comment]
v0.1.0 released!
