### ISSUE TITLE
Instrumentation framework does not encourage use of SpanBuilder-set attributes

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-auto-instr-java#230]
From https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/195#discussion_r391778237:
I would force the user of the instrumentation framework (with user I mean the one who implements concrete classes here) to provide the request already in startSpan, so that all attributes are set on the builder and thus available to samplers (and onStart callbacks of SpanProcessors). See spec: https://github.com/open-telemetry/opentelemetry-specification/blob/4ab7c2fb4964c14fe972b03b5bb6825573bafb24/specification/api-tracing.md#span-creation

> * Attributes - A collection of key-value pairs, with the same semantics as the ones settable with Span::SetAttributes. Additionally, these attributes may be used to make a sampling decision as noted in sampling description. An empty collection will be assumed if not specified.
>
>   Whenever possible, users SHOULD set any already known attributes at span creation instead of calling SetAttribute later.

**Comment by trask** [comment]
Hi @Oberon00! The reason we aren't setting span attributes on the span builder (yet) is because the current OpenTelemetry API release (0.2.0) does not support that. Once 0.3.0 is released, we are planning to address this. This work is tracked in #76.

**Comment by Oberon00** [comment]
Makes sense. I did not consider that you can only use released versions. I guess the opentelemetry-java package does not get released very often 😅

**Comment by trask** [comment]
Closing, hope that's ok, just added #303 to track this

**Comment by patsonluk** [comment]
Hi, we run into similar issue and wish to know the URL when doing sampling decision.

But it seems like with the change in https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/348/files , the `http.url` is still not available for example in the `Servlet3Advice`, the `DECORATOR` which [adds the `http.url` attribute](https://github.com/prydin/opentelemetry-auto-instr-java/blob/173106702163a5e01f16f75243f93d9ce78f4ad9/instrumentation/servlet/request-3.0/src/main/java/io/opentelemetry/auto/instrumentation/servlet/v3_0/Servlet3Advice.java#L85) is not run until the span is started.

Wondering if it's feasible to change the DECORATOR to allow a `beforeSpanStart` or even change the `onRequest` and `onConnection` to take `SpanBuilder` and have them executed before the span is started?

Many thanks in advance!

**Comment by trask** [comment]
Hi @patsonluk, can you open a new issue for this? It's a good point.

**Comment by patsonluk** [comment]
> Hi @patsonluk, can you open a new issue for this? It's a good point.

For sure #388 :)
