### ISSUE TITLE
Rewritable Tracer

### ISSUE THREAD

**Issue by safris** [open-telemetry/opentelemetry-auto-instr-java#309]
**Abstract**

The <ins>Rewritable Tracer</ins> allows one to rewrite data in the spans created by Integrations without having to modify the source code. A JSON config file defines a set of rules that modify trace information in the layer between the integration, and the exporter.

**Introduction**

The <ins>Rewritable Tracer</ins> is an idea inspired by the [OpenTracing Rewrite](https://github.com/opentracing-contrib/java-specialagent/tree/master/opentracing-rewrite) module that was originally suggested by @zeitlinger for the SpecialAgent project.

**Specification**
_The specification below applies to the OT API, and needs to be adapted to the OTel API._

1. <ins>Context</ins>
   The <ins>Rewritable Tracer</ins> will sit in the [Span Processor](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk.md#span-processor) layer, to be able to modify trace data generated by integrations in real time.

1. <ins>Inputs and Outputs</ins>
   Rules contain `input` (required) and `output` (optional) properties.

   * **Input (required)**
     The `input` property is required, as it defines the rule by which span data is matched. The `input` object contains 3 properties:

     1. `type`: The type of data to match (`tag`, `log`, or `operationName`).
     1. `key`: The key of the data (a string).
     1. `value`: The value of the data (a boolean, number, or string -- if a string, then the value is interpreted as a regular expression).

     _The `input` property can contain a value with a single `input` object, or an array with multiple `input` objects. If multiple `input` objects are provided, they will be considered with OR relationship._

     **Output (optional)**
     If `output` is omitted, then the matched data will be dropped.

     If `output` is provided, then the matched data will be rewritten.

     Like the `input` object, the `output` object follows the same schema:

     1. `type`: The type of data to which the matched data is to be rewritten (tag, log, or operationName).
     1. `key`: The key of the data to which the matched data is to be rewritten (a string).
         If `key` is omitted, then the key of the matched data will not be changed.
     1. `value`: The value of the data (a boolean, number, or string -- if a string, then the value is interpreted as a regular expression).
        If `value` is omitted, then the value of the matched data will not be changed.
        The `value` string may contain back references (i.e. `$1`, `$2`, etc) if the value in the `input` defines a regular expression with matching groups.

     The `output` property can contain a value with a single `output` object, or an array with multiple `output` objects. If multiple `output` objects are provided, they will be considered with AND relationship.

_This is a draft proposal, intended to spur discussion so we can come to a proposal for its v1 implementation._

Other similar prior art:
1. [java-api-extensions](https://github.com/opentracing-contrib/java-api-extensions)
1. [opentracing-proxy](https://github.com/zalando/opentracing-toolbox/tree/master/opentracing-proxy)

**Comment by zeitlinger** [comment]
@safris I've just checked the integration points of this project. It seems that RewritableTracer could be a standalone project:

1. `TracerProvider` can be [https://github.com/open-telemetry/opentelemetry-java/blob/master/api/src/main/java/io/opentelemetry/OpenTelemetry.java#L143](customized)
    1. which gives us the possibility to provide different `Tracer` instances to different instrumentations
    2. this would allow us to customize spans as they are created (the current strategy)
2. `SpanProcessor` can be [customized](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/f0354033b2f454c9b94a32ebb5903bbf96204617/agent-tooling/src/main/java/io/opentelemetry/auto/tooling/TracerInstaller.java#L54)
    1. which gives us the possibility to modify spans before they are exported
    2. we can still [identify](https://github.com/open-telemetry/opentelemetry-java/blob/38d9352a8482925a28cd4530b02f7acc15b9633d/sdk/src/main/java/io/opentelemetry/sdk/trace/ReadableSpan.java#L63) the instrumentation that created the span
    3. it would be convenient to be able to specify multiple `exporter.jar` entries

Both options would work as far as I can see.
The only [reference](https://github.com/open-telemetry/oteps/blob/0c9b077c49003316ad8639d0a9c0ec80b600ee23/text/0016-named-tracers.md#instrumentation-library-identification) I found doesn't seem to suggest which of the options should be preferred.

**Comment by zeitlinger** [comment]
I added this to the [Java SIG agenda](https://docs.google.com/document/d/1oHpisisco8J7Yk73ovx3eeXaokSMqgVuEuWNwPOajtY/edit#heading=h.d7bm6jmhvqm5).

Please tell me if you want to discuss this also in the auto-inst SIG.

**Comment by safris** [comment]
@zeitlinger, I believe the `SpanProcessor` would give us the granularity of control we'd need to implement a well-featured RewritableTracer. Thank you for adding the topic of this issue to the Java SIG. I'll make sure to attend it on April 17th. Currently, this issue is pinned to the auto-instr project, and we can put it on [the agenda](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw/edit#heading=h.ustyauocnsrm) for this coming Friday.

**Comment by zeitlinger** [comment]
@safris following up on the suggestion to include this functionality in the collector, I've created https://github.com/open-telemetry/opentelemetry-collector/pull/928 and https://github.com/open-telemetry/opentelemetry-collector/pull/929 - which should cover all use cases that were covered by rewritable tracer.

Hence I think this issue can be closed.

**Comment by safris** [comment]
Thanks for following up on this @zeitlinger. We'll continue the development in the collector issues you provided.
