### ISSUE TITLE
It looks like we are suppressing the embedded OpenTelemetry SDK's logging

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-auto-instr-java#335]
It looks like [PatchLogger](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/v0.2.2/agent-bootstrap/src/main/java/io/opentelemetry/auto/bootstrap/PatchLogger.java) doesn't delegate to the shaded SLF4J.

This probably wasn't a big issue previously because i think the only dependency that used java.util.logging was guava.

But definitely important now to capture the embedded OpenTelemetry SDK's logging.

Reported over gitter. Thanks @Oberon00!

**Comment by Oberon00** [comment]
Gitter link, for further reference: https://gitter.im/open-telemetry/opentelemetry-auto-instr-java?at=5e9dc6c7a412254f219f6adb (sorry to dig this issue up, please ignore)
