### ISSUE TITLE
Add support for SignalFx @Trace annotation

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-auto-instr-java#343]
Otel-auto supports some 3rd-party annotations to mark methods that should create new spans. This support is implemented by `io.opentelemetry.auto.instrumentation.traceannotation.TraceAnnotationsInstrumentation`. Currently it does not support SignalFx `com.signalfx.tracing.api.Trace`.

**Comment by safris** [comment]
This issue and PR relates to https://github.com/open-telemetry/opentelemetry-java/issues/813

**Comment by iNikem** [comment]
It is certainly related, but I think they are still independent. As long as Otel wants to support proprietary APIs, it still has to support those 3rd party annotations. Even after Otel gains its own `@Trace` annotation.
