### ISSUE TITLE
Allow to disable auto-instrumentation for specified methods

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-auto-instr-java#344]
There is a configuration property `ota.trace.classes.exclude`, which allows to exclude some classes from auto-instrumentation. I propose to add similar property `ota.trace.methods.exclude` to allow more fine-grained configuration: to exclude only specific methods from a class.

**Comment by trask** [comment]
I'm curious if these properties are only needed for working around instrumentation bugs, or if there are other use cases?

**Comment by iNikem** [comment]
Another use-case I can think of: some library out of user's control produces a huge amount of monitoring data either due to a bug or just high load. User may want to silence it.

**Comment by trask** [comment]
Have you seen the instrumentation-level silencing configuration yet:

https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/v0.2.2/agent-bootstrap/src/main/java/io/opentelemetry/auto/config/Config.java#L288

We discussed this a bit in last week's SIG meeting ([sorry for the somewhat jumbled notes](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw)).

Does this address what you are looking for?

**Comment by johnbley** [comment]
We (Splunk) have some customers who have over-instrumented their app and find a configuration-based approach more flexible than re-changing code, particularly as an immediate response.  Given that the (otel) code to enable this is fairly localized I find the feature pretty innocuous.

**Comment by iNikem** [comment]
@trask If you don't object this proposed change, can you please assign this task to me?

**Comment by trask** [comment]
@johnbley oh, do you mean over-instrumented using `@Trace` annotations? just want to understand the use case for needing method-level excludes, then good to go

**Comment by johnbley** [comment]
Yes, over-instrumenting with `@Trace` is what I meant.  Sorry for the confusing terminology.

**Comment by trask** [comment]
@johnbley got it, thanks! @iNikem all yours!
