### ISSUE TITLE
Cannot build against otel-java 0.4.0-snapshot

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-auto-instr-java#363]
It seems that Otel-java has several changes since last release of 0.3.0 that broke auto-instr. It currently does not compile against latest 0.4.0 snapshot. E.g. [NoopScope was removed](https://github.com/open-telemetry/opentelemetry-java/pull/1062) and several others.

This also raises the question about regular (nightly?) cross-compilation between the two repos. How we detect such breaking changes and fix their consequences?

**Comment by iNikem** [comment]
This issue also blocks #359

**Comment by trask** [comment]
This is a good topic for SIG meeting tomorrow, I added it to the [agenda](https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw)

**Comment by iNikem** [comment]
@trask in light of today discussion, should I fix this issue and make our master branch compatible with otel-java 0.4.0 snapshot? Or we want to wait for this until we ourselves release 0.3.0? The latter will mean that #359 cannot be done until after auto-instr 0.3.0 release.

Or, more precisely, it can be done, but in that new branch of auto-instr which will follow otel-java 0.4.0. Which makes total sense. #359 depends on the functionality that exists in otel-java 0.4.0, but not in 0.3.0. This mean that support for that functionality should be in auto-instr 0.4.0, and not 0.3.0 :) So, please, make that new branch for 0.4.0 :)

**Comment by trask** [comment]
👍

New branch: `depends-on-otel-java-snapshot`

Go ahead and send PRs to that branch.

Once otel-java releases `0.4.0` we can merge that branch over to master and bump the `depends-on-otel-java-snapshot` branch to depend on otel-java `0.5.0-SNAPSHOT`.
