### ISSUE TITLE
Don't use synchronous span processor

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-auto-instr-java#368]
Switch from `SimpleSpanProcessor` to `BatchSpansProcessor` or `DisruptorAsyncSpanProcessor`.

See https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/v0.2.2/agent-tooling/src/main/java/io/opentelemetry/auto/tooling/TracerInstaller.java#L72

**Comment by johnbley** [comment]
I can confirm that a simple one-line change to use the batch processor improves GC thrash/throughput 4-5x on a simple benchmark.
