### ISSUE TITLE
Add Zipkin exporter support

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-auto-instr-java#375]
Zipkin exporter is available now in otel-java 0.4.0-SNAPSHOT, and will be available soon in the otel-java 0.4.0 release.

**Comment by malafeev** [comment]
can I work on this issue and to be assigned? cannot do it myself.

**Comment by trask** [comment]
awesome! assigned to you

**Comment by malafeev** [comment]
blocked by https://github.com/open-telemetry/opentelemetry-java/issues/1182

**Comment by trask** [comment]
This should be unblocked now by the opentelemetry-java `0.4.1` release 👍

**Comment by malafeev** [comment]
great, I will proceed.

**Comment by malafeev** [comment]
zipkin exporter uses `HttpURLConnection` therefore it's self-traced. @trask is it possible to disable `HttpURLConnection` traces only for zipkin in the auto-exporter?

**Comment by trask** [comment]
Oh that's interesting! We don't normally have this problem since we exclude the exporter class loader from any bytecode instrumentation, but `HttpURLConnection` is in the bootstrap class loader 🙃.

I think probably the easiest thing is for us to configure Zipkin to use `OkHttpSender` instead, e.g.

```
ZipkinExporterConfiguration.builder()
    .setSender(OkHttpSender.create(zipkinEndpoint))
    .setServiceName(serviceName)
    .build()
```

**Comment by devinsba** [comment]
:+1: to what @trask trask said. The most common http reporter used by ZIpkin users is the OkHttp one, it is the default in spring-cloud-sleuth. The URLConnection one exists mostly in the case of classpath issues. (cc @adriancole in case he has any opinions)

That brings up a second thought for me. Can you create an issue to add configuration that would allow for using the other reporter options (kafka, rabbit, etc.)

**Comment by malafeev** [comment]
@devinsba I added OkHttpSender, and created #417 for other options

**Comment by malafeev** [comment]
done via https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/411
can be closed now
