### ISSUE TITLE
Document which instrumentation is enabled by default and which is not

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-auto-instr-java#383]
Maybe as an additional column on https://github.com/open-telemetry/opentelemetry-auto-instr-java#supported-java-libraries-and-frameworks, plus note about how to enable instrumentation that is not enabled by default.

**Comment by iNikem** [comment]
Why some instrumentations are disabled by default? Do we have any explanation for that anywhere in the doc?

**Comment by iNikem** [comment]
@trask I could do this, but I would prefer to add some explanation of "why" as well. Either to a particular disabled instrumentation or to common doc about general rule.

**Comment by trask** [comment]
Can you make list of instrumentation that's currently disabled by default? I added this to Thu SIG meeting agenda: https://docs.google.com/document/d/1WK9h4p55p8ZjPkxO75-ApI9m0wfea6ENZmMoFRvXSCw

> Review instrumentation that’s currently disabled by default.
> Do we want to keep them disabled by default?
> Write down the reason why for any that we want to keep disabled by default.

**Comment by iNikem** [comment]
The following instrumentations are disabled by default: jdbc-datasource, servlet-filter, grizzly, servlet-service, jetty, sparkjava

**Comment by iNikem** [comment]
From today's SIG meeting I understood, that servlet-filter and servlet-service probably should remain disabled (and documented) because of potential noise. All others can be enabled by default. Am I correct, @tylerbenson ?

**Comment by trask** [comment]
I'd suggest leaving `jdbc-datasource` disabled due to noise also. I checked, and you had to opt-in to get spans for `DataSource.getConnection` in Glowroot as well: https://github.com/glowroot/glowroot/blob/master/agent/plugins/jdbc-plugin/src/main/java/org/glowroot/agent/plugin/jdbc/DataSourceAspect.java#L71

IIRC, the noisiness is because that instrumentation ends up getting applied to connection pools (which implement DataSource), and so you get a span every time a connection is pulled from the connection pool, which while occasionally interesting, is mostly noise.
