### ISSUE TITLE
Support jTDS driver connection strings for SQL Server

### ISSUE THREAD

**Issue by sleighzy** [open-telemetry/opentelemetry-auto-instr-java#395]
The [JDBCConnectionUrlParser](https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/agent-bootstrap/src/main/java/io/opentelemetry/auto/bootstrap/instrumentation/jdbc/JDBCConnectionUrlParser.java) supports a number of databases and the associated connection strings for their drivers. Our company uses both the Microsoft driver and open source [jTDS](http://jtds.sourceforge.net/) driver for connecting to SQL Server databases. The url parsing logic in this class does not currently support that required by the jTDS driver.

**Comment by sleighzy** [comment]
I can contribute the additional parsing logic for this connection string if that is acceptable.

**Comment by trask** [comment]
That would be awesome! Assigning this issue to you 😄.
