### ISSUE TITLE
Add ability to Auto-Instrument non framework java methods

### ISSUE THREAD

**Issue by ddesjardins-splunk** [open-telemetry/opentelemetry-auto-instr-java#402]
Hello all,

In order for OpenTelemetry to yield a more complete set of span information in a trace, would like to see the ability to specify methods to be auto-instrumented that are custom implemented ( non framework ).  While we have @WithSpan that still requires a recompile of code and a change to source files, to many dev teams says "manual effort". If developers could specify a list of methods ( that they themselves authored ) to be auto-instrumented it would yield more span coverage with no source code impact and little work for dev teams.

**Comment by devinsba** [comment]
This is available as the property `ota.trace.methods`

**Comment by ddesjardins-splunk** [comment]
This is great to hear, I will test this. However, i am unsure usage. Assuming I am accessing this property and submitting a list of methods at runtime ? 

I will retract this request, just need to test it !!!

**Comment by ddesjardins-splunk** [comment]
Closed and validated working as intended !
