### ISSUE TITLE
Incorrect values for client span's Status

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-auto-instr-java#418]
`io.opentelemetry.auto.bootstrap.instrumentation.decorator.HttpClientDecorator#onResponse` currently sets client span status to either `OK` or `UNKNOWN`. One would expect that e.g. http status 404 will result in span status `NOT_FOUND`. Also 400 probably means `INVALID_ARGUMENT` etc.

I remember I saw somewhere some discussion about how http statuses should map to span statuses, but cannot find it at the moment.

**Comment by trask** [comment]
Here's the relevant spec: https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#status

**Comment by trask** [comment]
Probably a duplicate of #326?

**Comment by iNikem** [comment]
@trask indeed, this is a duplicate.
