### ISSUE TITLE
Span::setAttribute() doesn't accept null values

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-auto-instr-java#65]
The ```Span::setAttribute()``` method is commonly used in interceptors to copy attributes from an invocation to span attributes. This method will, by design, throw a ```NullPointerException``` if a null value is supplied. Given that many frameworks may treat certain attributes as optional, there's a chance that attributes with null values are present on the invocation objects. 

The current implementation instrumenters/decorators are wrapping the calls to ```setAttribute()``` in null-checking if-statements whenever it is suspected that a null value may be supplied.

However, since the exact rules for which attributes may contain null aren't well documented for all frameworks, there's a high risk that a null-check is omitted by mistake, causing hard to find errors at runtime.

Should we implement a ```setAttributeOrNull()``` method that can be used when the presence of null values isn't known? Should we change the behavior of ```setAttribute()```? What is the reason we don't allow null values in the first place? Could we change the behavior to make an assignment of a null value to an attribute a no-op?

**Comment by trask** [comment]
Can you open this in https://github.com/open-telemetry/opentelemetry-java? That is where this change would need to happen. (btw, I totally support this!)

**Comment by prydin** [comment]
OK. Will do. BTW, I'm seeing this issue in multiple packages. I think the original Datadog code was written without null-checking in mind. Leaving this check in place is a ticking bomb.

**Comment by prydin** [comment]
Linked issue: https://github.com/open-telemetry/opentelemetry-java/issues/765

**Comment by trask** [comment]
Yeah, the existing code does null-checking here https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/686f72e02f70657ba2b46e57276bfa60ce9a033f/java-agent/agent-tooling/src/main/java/io/opentelemetry/auto/tooling/AgentTracerImpl.java#L149, this problem is coming up when moving the instrumentation to using OpenTelemetry API directly.

**Comment by trask** [comment]
Closing (tracking subsequent cleanup in #76)
