### ISSUE TITLE
request.getAttribute(SPAN_ATTRIBUTE) returns an AgentSpan

### ISSUE THREAD

**Issue by prydin** [open-telemetry/opentelemetry-auto-instr-java#69]
Many of the instrumenters are obtaining the parent(?) span by calling ```request.getAttribute(SPAN_ATTRIBUTE)``` on the request passed through the context to ```OnMethodEnter```.  Here is an example:

https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/1d474353a5ea310966d44e85ece4bbb75282ae70/java-agent/instrumentation/spring-webmvc-3.1/src/main/java/io/opentelemetry/auto/instrumentation/springweb/HandlerAdapterInstrumentation.java#L72

This attribute, however, contains an ```AgentSpan```, which is not compatible with instrumenters refactored for the new APIs. Is there an alternative way of obtaining this span?

**Comment by prydin** [comment]
On closer inspection, it appears that this is handled in the ```servlet``` instrumentation package. It looks like this package has to be refactored prior to refactoring any of the application server packages. I guess I just got more work to do. :)

**Comment by prydin** [comment]
What exactly is this attribute supposed to contain? The current span? Couldn't we obtain that through ```tracer.getCurrentSpan()```? What's the relationship between the two?

**Comment by trask** [comment]
I think convert the attribute to contain `Span`.

`getCurrentSpan()` is the `Span` that is in scope at that time (tracked under the covers via `ThreadLocal`).

**Comment by prydin** [comment]
This has been fixed in opentelemetry-java. Closing.
